from datetime import timedelta
from django.core.management.base import BaseCommand
from django.utils import timezone
from store.models import Medicine


class Command(BaseCommand):
    help = 'Seed database with 20 tablets/capsules, 20 creams, and 10 syrups.'

    def handle(self, *args, **options):
        today = timezone.localdate()
        self.stdout.write(self.style.WARNING('Seeding inventory with 50 new items...'))

        medicines_data = [
            # --- 20 Tablets & Capsules ---
            {
                'name': 'Panadol 500mg',
                'generic_name': 'Paracetamol',
                'category': Medicine.TABLET,
                'manufacturer': 'GSK',
                'batch_number': 'PAN-2026',
                'expiry_date': today + timedelta(days=500),
                'purchase_price': 2.00,
                'sale_price': 3.50,
                'stock_quantity': 500,
                'reorder_level': 50,
                'barcode': '100010',
            },
            {
                'name': 'Panadol Extra',
                'generic_name': 'Paracetamol + Caffeine',
                'category': Medicine.TABLET,
                'manufacturer': 'GSK',
                'batch_number': 'PNX-401',
                'expiry_date': today + timedelta(days=450),
                'purchase_price': 3.00,
                'sale_price': 5.00,
                'stock_quantity': 400,
                'reorder_level': 40,
                'barcode': '100011',
            },
            {
                'name': 'Disprin 300mg',
                'generic_name': 'Aspirin',
                'category': Medicine.TABLET,
                'manufacturer': 'Reckitt Benckiser',
                'batch_number': 'DSP-882',
                'expiry_date': today + timedelta(days=600),
                'purchase_price': 1.50,
                'sale_price': 2.50,
                'stock_quantity': 350,
                'reorder_level': 30,
                'barcode': '100012',
            },
            {
                'name': 'Brufen 400mg',
                'generic_name': 'Ibuprofen',
                'category': Medicine.TABLET,
                'manufacturer': 'Abbott',
                'batch_number': 'BRF-102',
                'expiry_date': today + timedelta(days=550),
                'purchase_price': 4.00,
                'sale_price': 7.00,
                'stock_quantity': 300,
                'reorder_level': 40,
                'barcode': '100013',
            },
            {
                'name': 'Arinac Forte',
                'generic_name': 'Ibuprofen + Pseudoephedrine',
                'category': Medicine.TABLET,
                'manufacturer': 'Abbott',
                'batch_number': 'ARN-901',
                'expiry_date': today + timedelta(days=380),
                'purchase_price': 8.00,
                'sale_price': 12.00,
                'stock_quantity': 200,
                'reorder_level': 25,
                'barcode': '100014',
            },
            {
                'name': 'Flagyl 400mg',
                'generic_name': 'Metronidazole',
                'category': Medicine.TABLET,
                'manufacturer': 'Sanofi',
                'batch_number': 'FLG-331',
                'expiry_date': today + timedelta(days=400),
                'purchase_price': 3.50,
                'sale_price': 6.00,
                'stock_quantity': 250,
                'reorder_level': 30,
                'barcode': '100015',
            },
            {
                'name': 'Augmentin 625mg',
                'generic_name': 'Amoxicillin + Clavulanic Acid',
                'category': Medicine.TABLET,
                'manufacturer': 'GSK',
                'batch_number': 'AUG-772',
                'expiry_date': today + timedelta(days=360),
                'purchase_price': 28.00,
                'sale_price': 42.00,
                'stock_quantity': 150,
                'reorder_level': 20,
                'barcode': '100016',
            },
            {
                'name': 'Ciproxin 500mg',
                'generic_name': 'Ciprofloxacin',
                'category': Medicine.TABLET,
                'manufacturer': 'Bayer',
                'batch_number': 'CPX-509',
                'expiry_date': today + timedelta(days=480),
                'purchase_price': 22.00,
                'sale_price': 35.00,
                'stock_quantity': 100,
                'reorder_level': 15,
                'barcode': '100017',
            },
            {
                'name': 'Klaricid 250mg',
                'generic_name': 'Clarithromycin',
                'category': Medicine.TABLET,
                'manufacturer': 'Abbott',
                'batch_number': 'KLR-114',
                'expiry_date': today + timedelta(days=420),
                'purchase_price': 30.00,
                'sale_price': 48.00,
                'stock_quantity': 120,
                'reorder_level': 15,
                'barcode': '100018',
            },
            {
                'name': 'Risek 20mg',
                'generic_name': 'Omeprazole',
                'category': Medicine.CAPSULE,
                'manufacturer': 'Getz Pharma',
                'batch_number': 'RSK-201',
                'expiry_date': today + timedelta(days=520),
                'purchase_price': 15.00,
                'sale_price': 24.00,
                'stock_quantity': 300,
                'reorder_level': 35,
                'barcode': '100019',
            },
            {
                'name': 'Risek 40mg',
                'generic_name': 'Omeprazole',
                'category': Medicine.CAPSULE,
                'manufacturer': 'Getz Pharma',
                'batch_number': 'RSK-402',
                'expiry_date': today + timedelta(days=500),
                'purchase_price': 25.00,
                'sale_price': 38.00,
                'stock_quantity': 220,
                'reorder_level': 25,
                'barcode': '100020',
            },
            {
                'name': 'Zyrtec 10mg',
                'generic_name': 'Cetirizine Dihydrochloride',
                'category': Medicine.TABLET,
                'manufacturer': 'UCB',
                'batch_number': 'ZYR-881',
                'expiry_date': today + timedelta(days=490),
                'purchase_price': 8.00,
                'sale_price': 14.00,
                'stock_quantity': 180,
                'reorder_level': 20,
                'barcode': '100021',
            },
            {
                'name': 'Rigix 10mg',
                'generic_name': 'Cetirizine',
                'category': Medicine.TABLET,
                'manufacturer': 'AGP',
                'batch_number': 'RGX-304',
                'expiry_date': today + timedelta(days=460),
                'purchase_price': 6.00,
                'sale_price': 10.00,
                'stock_quantity': 250,
                'reorder_level': 30,
                'barcode': '100022',
            },
            {
                'name': 'Softin 10mg',
                'generic_name': 'Loratadine',
                'category': Medicine.TABLET,
                'manufacturer': 'Ferozsons',
                'batch_number': 'SFT-612',
                'expiry_date': today + timedelta(days=440),
                'purchase_price': 5.00,
                'sale_price': 9.00,
                'stock_quantity': 200,
                'reorder_level': 20,
                'barcode': '100023',
            },
            {
                'name': 'Surbex Z',
                'generic_name': 'Multivitamins + Zinc',
                'category': Medicine.TABLET,
                'manufacturer': 'Abbott',
                'batch_number': 'SBX-993',
                'expiry_date': today + timedelta(days=600),
                'purchase_price': 12.00,
                'sale_price': 18.00,
                'stock_quantity': 160,
                'reorder_level': 25,
                'barcode': '100024',
            },
            {
                'name': 'CAC 1000 Plus',
                'generic_name': 'Calcium + Vitamin C',
                'category': Medicine.TABLET,
                'manufacturer': 'GSK',
                'batch_number': 'CAC-105',
                'expiry_date': today + timedelta(days=350),
                'purchase_price': 18.00,
                'sale_price': 28.00,
                'stock_quantity': 140,
                'reorder_level': 20,
                'barcode': '100025',
            },
            {
                'name': 'Evion 400mg',
                'generic_name': 'Vitamin E',
                'category': Medicine.CAPSULE,
                'manufacturer': 'Merck',
                'batch_number': 'EVN-404',
                'expiry_date': today + timedelta(days=540),
                'purchase_price': 7.50,
                'sale_price': 12.00,
                'stock_quantity': 280,
                'reorder_level': 30,
                'barcode': '100026',
            },
            {
                'name': 'Ponstan 500mg',
                'generic_name': 'Mefenamic Acid',
                'category': Medicine.TABLET,
                'manufacturer': 'Pfizer',
                'batch_number': 'PNT-502',
                'expiry_date': today + timedelta(days=480),
                'purchase_price': 3.00,
                'sale_price': 5.50,
                'stock_quantity': 450,
                'reorder_level': 50,
                'barcode': '100027',
            },
            {
                'name': 'Nuberol Forte',
                'generic_name': 'Paracetamol + Orphenadrine',
                'category': Medicine.TABLET,
                'manufacturer': 'Searle',
                'batch_number': 'NUB-808',
                'expiry_date': today + timedelta(days=410),
                'purchase_price': 9.00,
                'sale_price': 15.00,
                'stock_quantity': 210,
                'reorder_level': 25,
                'barcode': '100028',
            },
            {
                'name': 'Leflox 500mg',
                'generic_name': 'Levofloxacin',
                'category': Medicine.TABLET,
                'manufacturer': 'Getz Pharma',
                'batch_number': 'LFX-505',
                'expiry_date': today + timedelta(days=470),
                'purchase_price': 26.00,
                'sale_price': 40.00,
                'stock_quantity': 110,
                'reorder_level': 15,
                'barcode': '100029',
            },

            # --- 20 Creams & Ointments ---
            {
                'name': 'Betnovate-N Cream 20g',
                'generic_name': 'Betamethasone + Neomycin',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'BTN-201',
                'expiry_date': today + timedelta(days=420),
                'purchase_price': 95.00,
                'sale_price': 135.00,
                'stock_quantity': 60,
                'reorder_level': 10,
                'barcode': '100030',
            },
            {
                'name': 'Betnovate-C Cream 20g',
                'generic_name': 'Betamethasone + Clioquinol',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'BTC-303',
                'expiry_date': today + timedelta(days=400),
                'purchase_price': 100.00,
                'sale_price': 140.00,
                'stock_quantity': 55,
                'reorder_level': 10,
                'barcode': '100031',
            },
            {
                'name': 'Dermovate Cream 20g',
                'generic_name': 'Clobetasol Propionate',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'DMV-901',
                'expiry_date': today + timedelta(days=450),
                'purchase_price': 110.00,
                'sale_price': 155.00,
                'stock_quantity': 45,
                'reorder_level': 10,
                'barcode': '100032',
            },
            {
                'name': 'Polyfax Skin Ointment 20g',
                'generic_name': 'Polymyxin B + Bacitracin',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'PFX-112',
                'expiry_date': today + timedelta(days=500),
                'purchase_price': 85.00,
                'sale_price': 120.00,
                'stock_quantity': 80,
                'reorder_level': 15,
                'barcode': '100033',
            },
            {
                'name': 'Polyfax Eye Ointment 6g',
                'generic_name': 'Polymyxin B + Bacitracin',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'PFE-606',
                'expiry_date': today + timedelta(days=360),
                'purchase_price': 65.00,
                'sale_price': 90.00,
                'stock_quantity': 70,
                'reorder_level': 12,
                'barcode': '100034',
            },
            {
                'name': 'Hydrozole Cream 20g',
                'generic_name': 'Hydrocortisone + Clotrimazole',
                'category': Medicine.CREAM,
                'manufacturer': 'Stiefel',
                'batch_number': 'HDZ-404',
                'expiry_date': today + timedelta(days=380),
                'purchase_price': 130.00,
                'sale_price': 185.00,
                'stock_quantity': 40,
                'reorder_level': 8,
                'barcode': '100035',
            },
            {
                'name': 'Canesten Cream 1% 20g',
                'generic_name': 'Clotrimazole',
                'category': Medicine.CREAM,
                'manufacturer': 'Bayer',
                'batch_number': 'CNS-801',
                'expiry_date': today + timedelta(days=480),
                'purchase_price': 140.00,
                'sale_price': 200.00,
                'stock_quantity': 50,
                'reorder_level': 10,
                'barcode': '100036',
            },
            {
                'name': 'Fucidin Cream 2% 15g',
                'generic_name': 'Fusidic Acid',
                'category': Medicine.CREAM,
                'manufacturer': 'LEO Pharma',
                'batch_number': 'FCD-202',
                'expiry_date': today + timedelta(days=440),
                'purchase_price': 160.00,
                'sale_price': 225.00,
                'stock_quantity': 35,
                'reorder_level': 8,
                'barcode': '100037',
            },
            {
                'name': 'Fucicort Cream 15g',
                'generic_name': 'Fusidic Acid + Betamethasone',
                'category': Medicine.CREAM,
                'manufacturer': 'LEO Pharma',
                'batch_number': 'FCC-505',
                'expiry_date': today + timedelta(days=420),
                'purchase_price': 180.00,
                'sale_price': 250.00,
                'stock_quantity': 30,
                'reorder_level': 8,
                'barcode': '100038',
            },
            {
                'name': 'Quench Cream 50g',
                'generic_name': 'Moisturizing Cream',
                'category': Medicine.CREAM,
                'manufacturer': 'Atco',
                'batch_number': 'QNC-101',
                'expiry_date': today + timedelta(days=600),
                'purchase_price': 220.00,
                'sale_price': 310.00,
                'stock_quantity': 25,
                'reorder_level': 5,
                'barcode': '100039',
            },
            {
                'name': 'Squa-Trax Ointment 20g',
                'generic_name': 'Salicylic Acid',
                'category': Medicine.CREAM,
                'manufacturer': 'Stiefel',
                'batch_number': 'SQT-707',
                'expiry_date': today + timedelta(days=390),
                'purchase_price': 115.00,
                'sale_price': 165.00,
                'stock_quantity': 30,
                'reorder_level': 6,
                'barcode': '100040',
            },
            {
                'name': 'Nizoral Cream 2% 15g',
                'generic_name': 'Ketoconazole',
                'category': Medicine.CREAM,
                'manufacturer': 'Johnson & Johnson',
                'batch_number': 'NZR-303',
                'expiry_date': today + timedelta(days=460),
                'purchase_price': 190.00,
                'sale_price': 270.00,
                'stock_quantity': 28,
                'reorder_level': 5,
                'barcode': '100041',
            },
            {
                'name': 'Cutivate Cream 15g',
                'generic_name': 'Fluticasone Propionate',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'CTV-881',
                'expiry_date': today + timedelta(days=430),
                'purchase_price': 150.00,
                'sale_price': 210.00,
                'stock_quantity': 35,
                'reorder_level': 8,
                'barcode': '100042',
            },
            {
                'name': 'Travocort Cream 15g',
                'generic_name': 'Isoconazole + Diflucortolone',
                'category': Medicine.CREAM,
                'manufacturer': 'Bayer',
                'batch_number': 'TVC-202',
                'expiry_date': today + timedelta(days=410),
                'purchase_price': 210.00,
                'sale_price': 295.00,
                'stock_quantity': 25,
                'reorder_level': 5,
                'barcode': '100043',
            },
            {
                'name': 'Voltral Emulgel 20g',
                'generic_name': 'Diclofenac Diethylamine',
                'category': Medicine.CREAM,
                'manufacturer': 'GSK',
                'batch_number': 'VLT-909',
                'expiry_date': today + timedelta(days=520),
                'purchase_price': 125.00,
                'sale_price': 175.00,
                'stock_quantity': 65,
                'reorder_level': 12,
                'barcode': '100044',
            },
            {
                'name': 'Mupirocin Ointment 2% 15g',
                'generic_name': 'Mupirocin',
                'category': Medicine.CREAM,
                'manufacturer': 'Getz Pharma',
                'batch_number': 'MPC-404',
                'expiry_date': today + timedelta(days=400),
                'purchase_price': 140.00,
                'sale_price': 195.00,
                'stock_quantity': 30,
                'reorder_level': 6,
                'barcode': '100045',
            },
            {
                'name': 'Loprox Cream 1% 15g',
                'generic_name': 'Ciclopirox Olamine',
                'category': Medicine.CREAM,
                'manufacturer': 'Sanofi',
                'batch_number': 'LPX-101',
                'expiry_date': today + timedelta(days=370),
                'purchase_price': 165.00,
                'sale_price': 230.00,
                'stock_quantity': 22,
                'reorder_level': 5,
                'barcode': '100046',
            },
            {
                'name': 'Advantan Cream 15g',
                'generic_name': 'Methylprednisolone Aceponate',
                'category': Medicine.CREAM,
                'manufacturer': 'Bayer',
                'batch_number': 'ADV-606',
                'expiry_date': today + timedelta(days=440),
                'purchase_price': 175.00,
                'sale_price': 245.00,
                'stock_quantity': 20,
                'reorder_level': 5,
                'barcode': '100047',
            },
            {
                'name': 'Caladryl Lotion 100ml',
                'generic_name': 'Calamine + Diphenhydramine',
                'category': Medicine.CREAM,
                'manufacturer': 'Searle',
                'batch_number': 'CLD-303',
                'expiry_date': today + timedelta(days=550),
                'purchase_price': 110.00,
                'sale_price': 160.00,
                'stock_quantity': 45,
                'reorder_level': 10,
                'barcode': '100048',
            },
            {
                'name': 'Burnol Cream 20g',
                'generic_name': 'Aminacrine + Cetrimide',
                'category': Medicine.CREAM,
                'manufacturer': 'Reckitt Benckiser',
                'batch_number': 'BNL-505',
                'expiry_date': today + timedelta(days=490),
                'purchase_price': 70.00,
                'sale_price': 100.00,
                'stock_quantity': 75,
                'reorder_level': 15,
                'barcode': '100049',
            },

            # --- 10 Syrups ---
            {
                'name': 'Hydryllin Syrup 120ml',
                'generic_name': 'Aminophylline + Diphenhydramine',
                'category': Medicine.SYRUP,
                'manufacturer': 'Searle',
                'batch_number': 'HDR-120',
                'expiry_date': today + timedelta(days=450),
                'purchase_price': 110.00,
                'sale_price': 155.00,
                'stock_quantity': 80,
                'reorder_level': 15,
                'barcode': '100050',
            },
            {
                'name': 'Hydryllin DM Syrup 120ml',
                'generic_name': 'Dextromethorphan + Diphenhydramine',
                'category': Medicine.SYRUP,
                'manufacturer': 'Searle',
                'batch_number': 'HDM-121',
                'expiry_date': today + timedelta(days=440),
                'purchase_price': 120.00,
                'sale_price': 170.00,
                'stock_quantity': 75,
                'reorder_level': 15,
                'barcode': '100051',
            },
            {
                'name': 'Acefyl Syrup 120ml',
                'generic_name': 'Acefylline Piperazine',
                'category': Medicine.SYRUP,
                'manufacturer': 'Caraway',
                'batch_number': 'ACF-909',
                'expiry_date': today + timedelta(days=480),
                'purchase_price': 90.00,
                'sale_price': 130.00,
                'stock_quantity': 60,
                'reorder_level': 12,
                'barcode': '100052',
            },
            {
                'name': 'Cosepin Syrup 120ml',
                'generic_name': 'Diphenhydramine + Ammonium Chloride',
                'category': Medicine.SYRUP,
                'manufacturer': 'Atco',
                'batch_number': 'CSP-303',
                'expiry_date': today + timedelta(days=400),
                'purchase_price': 85.00,
                'sale_price': 125.00,
                'stock_quantity': 50,
                'reorder_level': 10,
                'barcode': '100053',
            },
            {
                'name': 'Pulmonol Syrup 120ml',
                'generic_name': 'Cough Formula Syrup',
                'category': Medicine.SYRUP,
                'manufacturer': 'CCL Pharma',
                'batch_number': 'PML-606',
                'expiry_date': today + timedelta(days=420),
                'purchase_price': 105.00,
                'sale_price': 150.00,
                'stock_quantity': 65,
                'reorder_level': 12,
                'barcode': '100054',
            },
            {
                'name': 'Brufen Syrup 120ml',
                'generic_name': 'Ibuprofen 100mg/5ml',
                'category': Medicine.SYRUP,
                'manufacturer': 'Abbott',
                'batch_number': 'BFS-202',
                'expiry_date': today + timedelta(days=500),
                'purchase_price': 95.00,
                'sale_price': 140.00,
                'stock_quantity': 90,
                'reorder_level': 15,
                'barcode': '100055',
            },
            {
                'name': 'Tylenol Cold/Flu Syrup 120ml',
                'generic_name': 'Paracetamol + Chlorpheniramine',
                'category': Medicine.SYRUP,
                'manufacturer': 'Kenvue',
                'batch_number': 'TYL-404',
                'expiry_date': today + timedelta(days=460),
                'purchase_price': 130.00,
                'sale_price': 185.00,
                'stock_quantity': 40,
                'reorder_level': 8,
                'barcode': '100056',
            },
            {
                'name': 'Ventolin Syrup 120ml',
                'generic_name': 'Salbutamol 2mg/5ml',
                'category': Medicine.SYRUP,
                'manufacturer': 'GSK',
                'batch_number': 'VNT-808',
                'expiry_date': today + timedelta(days=430),
                'purchase_price': 75.00,
                'sale_price': 110.00,
                'stock_quantity': 70,
                'reorder_level': 12,
                'barcode': '100057',
            },
            {
                'name': 'Rigix Syrup 60ml',
                'generic_name': 'Cetirizine 5mg/5ml',
                'category': Medicine.SYRUP,
                'manufacturer': 'AGP',
                'batch_number': 'RGS-101',
                'expiry_date': today + timedelta(days=490),
                'purchase_price': 80.00,
                'sale_price': 115.00,
                'stock_quantity': 55,
                'reorder_level': 10,
                'barcode': '100058',
            },
            {
                'name': 'Entamizole Syrup 90ml',
                'generic_name': 'Metronidazole + Diloxanide',
                'category': Medicine.SYRUP,
                'manufacturer': 'Searle',
                'batch_number': 'ENT-909',
                'expiry_date': today + timedelta(days=410),
                'purchase_price': 115.00,
                'sale_price': 165.00,
                'stock_quantity': 48,
                'reorder_level': 10,
                'barcode': '100059',
            },
        ]

        count = 0
        for data in medicines_data:
            Medicine.objects.update_or_create(barcode=data['barcode'], defaults=data)
            count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully added {count} inventory items!'))
